#!/usr/bin/env node
import path from 'path';
import caporal from '@caporal/core';
import * as url from 'url';

const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

const script = await import(path.join(__dirname, 'src/run.js'));
script.run({
  caporal: caporal.default,
  projectRoot: __dirname,
  scriptsIndexModule: `./scripts/index.js`
});
