#!/usr/bin/env node
import caporal from '@caporal/core';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const script = await import(path.join(__dirname, 'src/run.js'));
script.run({
  caporal: caporal.default,
  projectRoot: __dirname,
  scriptsIndexModule: `./scripts/index.js`
});
